name: Terraform AWS Infra

on:
  push:
    branches:
      - main
    paths-ignore:
      - '**/README.MD'
      - '**/README.md'
      - '.github/workflows/**'
  pull_request:
    branches:
      - main
  workflow_dispatch:

env:
  TF_WORKING_DIR: environments/dev
  TF_VAR_public_key: ${{ secrets.PUBLIC_KEY }}

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ vars.AWS_REGION }}

      - name: Install Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.5.0

      - name: Initialize Terraform
        run: terraform init
        working-directory: ${{ env.TF_WORKING_DIR }}

      - name: Terraform Format
        working-directory: ${{ env.TF_WORKING_DIR }}
        run: terraform fmt -check

      - name: Validate Terraform configuration
        run: terraform validate
        working-directory: ${{ env.TF_WORKING_DIR }}

      - name: Plan Terraform changes
        run: terraform plan -out=tfplan
        working-directory: ${{ env.TF_WORKING_DIR }}

      - name: Apply Terraform changes
        run: terraform apply -auto-approve tfplan
        working-directory: ${{ env.TF_WORKING_DIR }}
