name: Terraform Destroy

on:
  workflow_dispatch:

env:
  TF_WORKING_DIR: environments/dev
  TF_VAR_public_key: ${{ secrets.PUBLIC_KEY }}

jobs:
  destroy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ vars.AWS_REGION }}

      - name: Install Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.5.0

      - name: Initialize Terraform
        run: terraform init
        working-directory: ${{ env.TF_WORKING_DIR }}

      - name: Destroy Terraform resources
        run: terraform destroy -auto-approve
        working-directory: ${{ env.TF_WORKING_DIR }}